name: mcmodpackmanager_reborn
description: Manage your modpacks with ease!
publish_to: 'none'

version: 8.0.1+0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_platform_widgets: ^3.3.2
  dynamic_color: ^1.6.3
  get: ^4.6.5
  get_storage:
    git:
      url: https://github.com/mrquantumoff/get_storage.git
      ref: v2.2.3
  flutter_localizations:
    sdk: flutter
  intl: any
  ffi: ^2.0.1
  window_manager: ^0.3.2
  package_info_plus: ^3.1.2
  file_picker: ^5.2.11
  http: ^0.13.6
  path_provider: ^2.0.14
  archive: ^3.3.7
  flutter_platform_alert: ^0.3.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.5
  protocol_handler: ^0.1.5
  device_info_plus: ^8.2.2
  dart_ipify: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  msix: ^3.11.1
  flutter_launcher_icons: ^0.13.1
flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/logo256.png
    - assets/icons/logo.svg

flutter_icons:
  windows:
    generate: true
    image_path: assets/icons/logo.ico
    icon_size: 128
  macos:
    generate: true
    image_path: assets/icons/logo.png
    icon_size: 256
msix_config:
  display_name: MC Modpack Manager
  publisher_display_name: MrQuantumOFF (Demir Yerli)
  publisher: CN=010914FC-8843-4963-A3FE-E3E06E6D9F53
  identity_name: 58734MrQuantumOFFDemirYer.MinecraftModpackManagerR
  msix_version: 8.0.1.0
  logo_path: .\assets\icons\logo.ico
  store: true
  protocol-activation: curseforge, mcmodpackmanager
  app_uri_handler_hosts: www.curseforge.com, curseforge.com, beta.curseforge.com, modrinth.com
  languages: en-us, uk-ua, tr-tr
  capabilities: internetClient, broadFileSystemAccess